apiVersion: v1
kind: Service
metadata:
  name: rain-api
  namespace: rain-mlops
spec:
  type: NodePort
  selector:
    app: rain-api
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      nodePort: 30080
